GET http://localhost:8080/instructor/all
Content-Type: application/json

###

POST http://localhost:8080/instructor/add
Content-Type: application/json

{
  "first_name": "Sarvar",
  "last_name": "Eshmatov",
  "details": {
   "channel_name": "eduraka",
   "hobby": "running"
  }
}

###

DELETE http://localhost:8080/instructor/d/1

###
GET http://localhost:8080/instructor/get/
Content-Type: application/json